[workspace]
members = [
    "day01-calorie-counting",
    "day02-rock-paper-scissors",
    "day03-rucksack-reorganisation",
    "day04-camp-cleanup",
    "day05-supply-stacks",
    "day06-tuning-trouble",
]
